### ISSUE TITLE
Resources and Opportunities pages

### ISSUE THREAD

**Issue by alex-418** [BCcampus/tlpd#36]
1. Go into the backend, create the categories (resources, opportunities). 

2. Create posts in each category, and they will be automatically added to the corresponding category archive page. 

3. Create menu items for each category.

**Comment by BCcLeva** [comment]
Hi there- Do I have permissions to ADD categories?  I'm able to add TAGS but not sure about Categories.

**Comment by BCcLeva** [comment]
Was commenting. Did not want to close this issue.

**Comment by bdolor** [comment]
yes, you are able to add categories with your permission level.

**Comment by BCcLeva** [comment]
Jen added as I don't see the option to do so per 
![screen shot 2018-06-12 at 10 24 33 am](https://user-images.githubusercontent.com/34721375/41306801-261a1b98-6e2c-11e8-8a22-519f404c3fcf.png)

**Comment by bdolor** [comment]
located in the dashboard, under Posts->Categories

![image](https://user-images.githubusercontent.com/2048170/41306887-6c422e26-6e2c-11e8-84c4-71d6d5c7aba2.png)

**Comment by BCcLeva** [comment]
My options under "posts" are 
!
![screen shot 2018-06-12 at 10 45 01 am](https://user-images.githubusercontent.com/34721375/41307317-b52c294c-6e2d-11e8-9f05-8b8791a1d0ca.png)

**Comment by bdolor** [comment]
do you have more than one account?

**Comment by BCcLeva** [comment]
hmm that's possible. Let me check.

**Comment by BCcLeva** [comment]
Yes that's the reason it doesn't appear. I must have been using another test account with User privileges not Admin.Thanks.

**Comment by jgrajkowski** [comment]
I'm working with Alex on item 3 this afternoon as the menu items appear to be hardcoded (and aren't showing the same in the dashboard as they do in EYPD).  If he or I don't notice it's done, Alex is likely looking into it.

**Comment by alex-418** [comment]
@jgrajkowski once https://github.com/BCcampus/tlpd/pull/48 is merged you should have control of the menu again

**Comment by jgrajkowski** [comment]
Menu updated.

- [ ] Events currently links back to home because of search -- need to determine an "Events" page + content.
- [ ] Resources links to the aggregated posts lists for all items tagged "Resources"; the same for "Opportunities" -- will need to review/determine styling of these pages before next sprint
- [ ] Add New -- Presently just links to the Post an Event.  Need to determine what to do with the Edit Event (I technically have it below Post Event/Add New in the menu per the Dashboard, but as it does not have a drop-down it does not show) as well as to communicate the mechanism for adding Resources and/or Opportunities.

So, this item can be closed but includes considerations for next.

**Comment by BCcLeva** [comment]
After consultation with the Learning and Teaching team yesterday it was advised that we hide or remove the display of the top menu nav for now and the New Resources and New Opportunities for the purposes of user testing. Let me know if this is possible. Thanks.

**Comment by bdolor** [comment]
removing Resources/Opportunity tabs as well?

**Comment by BCcLeva** [comment]
Yes for purposes of user testing probably best to not introduce at this stage but helpful to have for internal discussion.

**Comment by bdolor** [comment]
complete
