### ISSUE TITLE
Design asset values 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/tlpd#4]
decisions around 
- font
- colour scheme
- layout 
- heading sizes

**Comment by BCcLeva** [comment]
I have met with Maggie Caspar April 3rd who is sending me a quote for web identity for this project, associated graphics for print/social media and UX work.

**Comment by BCcLeva** [comment]
the arrangement with Maggie fell through. i'm meeting with another graphic designer this AM april 25.

**Comment by BCcLeva** [comment]
For font, layout and heading sizers I suggest we go with what is being currently used by EYPD
For the colour scheme we can chose a few colours in a palette that will enhance the placeholder graphic.

**Comment by alex-418** [comment]
@jgrajkowski to provide

**Comment by jgrajkowski** [comment]
If the notes below have a * (usually on font size) it's because I'm not totally sure; the mockup is partly done in illustrator on top of a screenshot (the Chrome inspect/console only goes so far so fast) and I doubt the values are exactly correct.

- [ ] - Logo colours: purple #8e53a1, green #73bf44, blue #2584c5, grey #818181, subheader blue #005482.
- [ ] - Body & Search Labels: Montserrat Light, approx 12pt*, #005482 
- [ ] - H1 + Menu: Montserrat Bold, approx 14pt, allcaps, #74c044
- [ ] - Top row background: #f7f8fc
- [ ] - Button Colour: #74c044  + Text: (H1 + #fff)
- [ ] - New + Noteworthy: border #2584c5, 1pt

(edits to come, just saving before I lose this)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/tlpd/pull/47
